### ISSUE TITLE
Kebab Documentation

### ISSUE THREAD

**Issue by KacperWojdak** [kibolApp/KebabWeb#9]
This task has no programming issue. The main goal is to gather information about all of the kebabs in the city of Legnica that will be used in other issues a.o. #7 , #13, #14

**Comment by PiotrFedak** [comment]
... No description provided

**Comment by KacperWojdak** [comment]
[Kababs.docx](https://github.com/user-attachments/files/18188964/Kababs.docx)
[Kababs.pdf](https://github.com/user-attachments/files/18188965/Kababs.pdf)
